import type { Metadata } from "next";
import "./../globals.css";
import { Footer } from "../components/footer";
import { Header } from "../components/header";
import {I18nProviderClient} from '@/locales/client';
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({params: {locale}, children}: { params: { locale: string }, children: ReactNode }) {
  return (
    <html lang={locale}>
      <body>
        <I18nProviderClient locale={locale}>
          <Header/>
          {children}
          <Footer/>
        </I18nProviderClient>
      </body>
    </html>
  );
}
